name: randomlunch-api

accounts:
  - name: randomlunchdev
    account_number: '952080297105'
    default_region: eu-west-1
  - name: randomlunchprod
    account_number: '206670076487'
    default_region: eu-west-1

templates:
  account:
    path: cloudformation/account
    params:
      AccountName: '{{ account.name }}'
  stage:
    path: cloudformation/stage
    params:
      StageName: '{{ stage.name }}'
      DomainName: randomlunch.burib.net
      ApplicationName: randomlunch

stages:
  default:
    account: randomlunchdev
    region: eu-west-1
  dev:
    account: randomlunchdev
    region: eu-west-1
  prod:
    account: randomlunchprod
    region: eu-west-1

services:
  randomlunch-api:
    type: lambda-apigateway

    build:
      working_dir: '.'
      dependencies: requirements.txt
      include:
        - randomlunch/
        - main.py
        - gateway/randomlunch-api-v1.yml
      dist_dir: dist

    deploy:
      apigateway:
        rest_api_name: randomlunch-api
        swagger_template: gateway/randomlunch-api-v1.yml
        domains:
          - domain_name: '{{ stage.outputs.CustomDomainName }}'
            base_path: '/'
        integration:
          type: AWS_PROXY
          uri: 'arn:aws:apigateway:{{ stage.region }}:lambda:path/2015-03-31/functions/arn:aws:lambda:{{ stage.region }}:{{ account.account_number }}:function:RandomLunchAPI:{{ stage.name }}/invocations'
          credentials: '{{ account.outputs.APIGatewayInvokeRoleArn }}'

      lambda_function_configuration:
        FunctionName: RandomLunchAPI
        Role: '{{ stage.outputs.LambdaExecutionRoleArn }}'
        Handler: main.lambda_handler
        Timeout: 30
        MemorySize: 128
        Runtime: python3.6
        TracingConfig:
          Mode: Active

      parameters:
        stages:
          default:
            - name: log_level
              value: debug
            - name: stage
              value: '{{ stage.name }}'
          dev: []
          prod:
            - name: log_level
              value: info
